application: yey-checklist
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: 2.6

handlers:
- url: /statics
  static_dir: statics
  
- url: /ajax/.*
  script: more_items.app

- url: /
  script: index.app
  
- url: /create/.*
  script: create.app
  